#!/bin/bash

# Program to output a system information page
# 	1. Open page
#	2. Open page header
#	3. Set page title
#	4. Close page header
#	5. Open page body
#	6. Output page heading
#	7. Output timestamp
#		Output System uptime and load
#		Output Disk space
#		Output Home space
#	8. Close page body
#	9. Close page
###############################################

# Function definition
###############################################

report_uptime () {
	cat <<- _EOF_
		<H2>System Uptime</H2>
		<PRE>$(uptime)</PRE>
		_EOF_
#	echo "Function report_uptime executed."
	return
}

report_disk_space() {
	cat <<- _EOF_
		<H2>Disk Space Utilization</H2>
		<PRE>$(df -h)</PRE>
		_EOF_
#	echo "Function report_disk_space executed."
	return
}

report_home_space() {
	cat <<- _EOF_
		<H2>Home Space Utilization</H2>
		<PRE>$(du -sh /home/*)</PRE>
		_EOF_
#	echo "Function report_home_space executed."
	return
}

# Main program starts here
###############################################

TITLE="System Information Report for $HOSTNAME"
CURRENT_TIME=$(date +"%x %r %Z")
TIME_STAMP="Generated $CURRENT_TIME, by $USER"

cat << _EOF_
<HTML>
	<HEAD>
		<TITLE>$TITLE</TITLE>
	</HEAD>
	<BODY>
		<H1>$TITLE</H1>
		<P>$TIME_STAMP</P>
		$(report_uptime)
		$(report_disk_space)
		$(report_home_space)
	</BODY>
</HTML>
_EOF_
